import arcade


class Theme:
    COLOR_HIGHLIGHTED_CATEGORY_SECTION = arcade.color.AERO_BLUE
    FONT_SIZE_DETAILS_SECTION = 10
    FONT_NAME = ('Source Code Pro', 'Monospace', 'Courier New', 'Consolas', 'Console', 'Roboto Mono', 'Menlo')
    COLOR_CROSS_HAIR_LINES = (255, 255, 0, 175)
    COLOR_TIMELINE_BACKGROUND = arcade.color.BLACK

    COLOR_MESSAGE_SECTION_BACKGROUND = arcade.color.ARSENIC
    COLOR_MESSAGE_SECTION_FONT_COLOR = arcade.color.WHITE

    COLOR_DETAIL_SECTION_BACKGROUND = arcade.color.ARSENIC
    COLOR_DETAIL_SECTION_FONT_COLOR = arcade.color.WHITE


class Layout:

    CATEGORY_BAR_WIDTH = 20
    COLOR_LEGEND_BAR_HEIGHT = 20
    ZOOM_DATE_RANGE_DISPLAY_BAR_HEIGHT = 20
    MESSAGE_SECTION_HEIGHT = 100
    MESSAGE_SECTION_LEFT = 0
    MESSAGE_SECTION_RIGHT_OFFSET = 0
    DETAIL_SECTION_HEIGHT = 120

    COLOR_LEGEND_BAR_RIGHT_OFFSET = 0
    COLOR_LEGEND_BAR_TOP_OFFSET = 0
    COLOR_LEGEND_BAR_LEFT = 0

    VERTICAL_SCROLL_BAR_WIDTH = 10
    VERTICAL_SCROLL_BAR_RIGHT_OFFSET = 0

    ZOOM_DATE_RANGE_DISPLAY_BAR_LEFT = CATEGORY_BAR_WIDTH
    ZOOM_DATE_RANGE_DISPLAY_BAR_TOP_OFFSET = COLOR_LEGEND_BAR_TOP_OFFSET + COLOR_LEGEND_BAR_HEIGHT

    CATEGORY_BAR_LEFT = 0
    CATEGORY_BAR_TOP_OFFSET = ZOOM_DATE_RANGE_DISPLAY_BAR_TOP_OFFSET + ZOOM_DATE_RANGE_DISPLAY_BAR_HEIGHT

    HORIZONTAL_SCROLL_BAR_HEIGHT = 10
    HORIZONTAL_SCROLL_BAR_RIGHT_OFFSET = VERTICAL_SCROLL_BAR_RIGHT_OFFSET + VERTICAL_SCROLL_BAR_WIDTH
    HORIZONTAL_SCROLL_BAR_LEFT = CATEGORY_BAR_LEFT + CATEGORY_BAR_WIDTH

    ZOOM_DATE_RANGE_DISPLAY_BAR_RIGHT_OFFSET = VERTICAL_SCROLL_BAR_RIGHT_OFFSET + VERTICAL_SCROLL_BAR_WIDTH

    DETAIL_SECTION_LEFT = 0
    DETAIL_SECTION_RIGHT_OFFSET = 0
    DETAIL_SECTION_BOTTOM = 0
    MESSAGE_SECTION_BOTTOM = DETAIL_SECTION_BOTTOM + DETAIL_SECTION_HEIGHT
    MESSAGE_SECTION_TOP = MESSAGE_SECTION_BOTTOM + MESSAGE_SECTION_HEIGHT

    HORIZONTAL_SCROLL_BAR_BOTTOM = MESSAGE_SECTION_TOP
    HORIZONTAL_SCROLL_BAR_TOP = HORIZONTAL_SCROLL_BAR_BOTTOM + HORIZONTAL_SCROLL_BAR_HEIGHT

    CATEGORY_BAR_BOTTOM = HORIZONTAL_SCROLL_BAR_TOP

    VERTICAL_SCROLL_BAR_BOTTOM = CATEGORY_BAR_BOTTOM
    VERTICAL_SCROLL_BAR_TOP_OFFSET = CATEGORY_BAR_TOP_OFFSET

    GRAPH_SECTION_BOTTOM = HORIZONTAL_SCROLL_BAR_BOTTOM

